name: follow back script
on:
  schedule:
    - cron: "0 0 * * FRI"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  followback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install node-fetch
      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.AGENT_TOKEN }}        
        run: node script.js
          
